# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)_$(Rev:rrrr)

variables:
  - group: Docker Maverick
  - name: buildConfiguration
    value: 'Release'
  - name: netcoreSdkVersion
    value: '3.1.x'
  - name: buildRevision
    value: $[counter(format('{0}-{1}', variables['Build.Repository.Name'], variables['Build.SourceBranchName']), 1)]
  - name: projectLocation
    value: .
  - name: projectFile
    value: ModernWpf Community Toolkit.sln

trigger:
  branches:
    include:
      - master
      - develop
  paths:
    exclude:
      - azure-pipelines.yml

resources:
  repositories:
    - repository: templates
      type: git
      name: A365/PipelineTemplates
      ref:  'refs/heads/master'

stages:
  - stage: Build
    jobs:
      - job: Application
        pool: 'A365VSTS'
        steps:
        # make sure to use the proper SDK
        - task: UseDotNet@2
          displayName: 'use DotnetCore-SDK "$(netcoreSdkVersion)"'
          inputs:
            packageType: 'sdk'
            version: '$(netcoreSdkVersion)'        

        # build nuget package of Document.Utilities
        - template: build-nuget.yaml@templates
          parameters:
            projectLocation: $(projectLocation)
            projectFile: $(projectFile)
            reusePreviousGeneratedVersion: false
            executeTests: true
            pushPackages: true