# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  project: '**/ModernWpf.Toolkit.UI.Controls.Markdown.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'


- task: DotNetCoreCLI@2
  displayName: package NugetPackage
  inputs:
    command: 'pack'
    packagesToPack: '$(project)'
    configuration: '$(BuildConfiguration)'
    packDirectory: '$(Build.ArtifactStagingDirectory)'
    nobuild: true
    versioningScheme: 'byBuildNumber'
    
- task: DotNetCoreCLI@2
  displayName: push NugetPackages
  condition: and(succeeded(), and(not(endsWith(variables['Build.BuildNumber'], 'DRAFT')), ne(variables['Build.Reason'], 'PullRequest')))
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '$(nugetFeed)'